basketball_app/urls.py
from django.contrib import admin
from django.urls import path
from website_basketball.views import UserAddView, LoginView, LogoutView, HomePageView, StatisticsCreateView,\
    StatisticsShowView, TeamShowView, TeamCreateView, PlayerEditView, TournamentsListView, TournamentCreateView,\
    TeamWinsAddView, TournamentTableView, TeamPlayerDeleteView, TeamPlayerAddView, MatchCreateView,\
    HistoryMatchesView, StadiumCreate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name="home_page"),
    path('add-user/', UserAddView.as_view(), name="add_user"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('statistics/', StatisticsShowView.as_view(), name="statistics"),
    path('statistics-create/', StatisticsCreateView.as_view(), name="statistics_create"),
    path('team/', TeamShowView.as_view(), name="team_show"),
    path('team-create/', TeamCreateView.as_view(), name="team_create"),
    path('edit-account/', PlayerEditView.as_view(), name="user_edit"),
    path('tournament/', TournamentsListView.as_view(), name="tournament"),
    path('tournament-create/', TournamentCreateView.as_view(), name="tournament_create"),
    path('team-wins-add/', TeamWinsAddView.as_view(), name="team_winds_add"),
    path('table/', TournamentTableView.as_view(), name='table'),
    path('player-delete/', TeamPlayerDeleteView.as_view(), name='player_delete_team'),
    path('player-add/', TeamPlayerAddView.as_view(), name='player_add_team'),
    path('stadium-match-create/', MatchCreateView.as_view(), name='stadium_history_create'),
    path('stadium-history/', HistoryMatchesView.as_view()),
    path('stadium-create/', StadiumCreate.as_view()),
]

website_basketball/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Tournament(models.Model):
    name = models.CharField(max_length=64, verbose_name="Nazwa turnieju")

    def __str__(self):
        return self.name


class Team(models.Model):
    team_name = models.CharField(max_length=64, unique=True, verbose_name="Nazwa drużyny")
    points_in_tournament = models.IntegerField(verbose_name="Liczba punktów", default=0)
    wins = models.IntegerField(verbose_name="Wygrane mecze w turnieju", default=0)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, null=True)

    class Meta:
        permissions = (
            ("add_wins", "Can add wins for Team"),
        )

    def __str__(self):
        return self.team_name


class Player(AbstractUser):
    date_of_birth = models.DateField(null=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, verbose_name="Drużyna", null=True)

    def __str__(self):
        return self.first_name


class Statistics(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, verbose_name="Drużyna")
    matches_played = models.IntegerField(verbose_name="Liczba zagranych meczy")
    total_points = models.IntegerField(verbose_name="Liczba zdobytych punktów")
    total_wins = models.IntegerField(verbose_name="Liczba wygranych meczy")


class Stadium(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nazwa stadionu')
    team = models.ManyToManyField(Team, null=True)
    date = models.DateField(null=True)
    statistics = models.ForeignKey(Statistics, on_delete=models.CASCADE, null=True, verbose_name='Statystyki')

    class Meta:
        permissions = (
            ("add_match", "Can add matches to the history"),
        )

    def __str__(self):
        return self.name

website_basketball/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Team, Tournament, Statistics, Player, Stadium
from django.contrib.auth import authenticate, login, logout
from .forms import UserAddForm, LoginForm, StatisticsCreateForm, TeamCreateForm, UserEditForm, TournamentCreateForm,\
    TeamWinsAddForm, TeamPlayerDeleteForm, TeamPlayerAddForm, StadiumCreateForm, StadiumHistoryFinder, MatchCreateForm
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db import IntegrityError


class HomePageView(View):
    def get(self, request):
        return render(request, "home_page.html")
    """ Strona główna wyświetla linki z przekierowaniami do różnych widoków """


class UserAddView(View):
    def get(self, request):
        form = UserAddForm()
        return render(request, "user_add.html", {'form': form})

    def post(self, request):
        form = UserAddForm(request.POST)
        if form.is_valid():
            try:
                Player.objects.create_user(username=form.cleaned_data['login'],
                                           password=form.cleaned_data['password'],
                                           email=form.cleaned_data['email'],
                                           first_name=form.cleaned_data['first_name'],
                                           last_name=form.cleaned_data['last_name'],
                                           date_of_birth=form.cleaned_data['date_of_birth'])
                return redirect('/login/')
            except IntegrityError:
                return render(request, "user_add.html", {'form': form, 'info': 'Użytkownik o podanym loginie istnieje!'})
        else:
            return render(request, "user_add.html", {'form': form, 'info': 'Wypełnij poprawnie wszystkie pola!'})

    """ Wchodząc metodą GET pokazuje pusty formularz rejestracyjny,
    a metodą POST wysyła formularz i zapisuje do bazy danych jeżeli jest poprawny """


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, "login.html", {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['login'],
                                password=form.cleaned_data['password'])
            if user:
                login(request, user)
                return redirect('/')
            else:
                return render(request, "login.html", {'form': form, 'info': "Błędny login lub hasło!"})

    """ Po wejściu na stronę logowania metodą GET wyświetla pusty formularz,
     a po wejściu metodą POST wysyła dane z formularza i po wpisaniu poprawnych danych loguje użytkownika na stronę """


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('/')

    """ Po wciśnięciu przycisku wyloguj, wyloguje użytkownika ze strony i przekierowuje na stronę główną"""


class StatisticsCreateView(PermissionRequiredMixin, View):
    permission_required = 'website_basketball.add_statistics'
    permission_denied_message = 'Nie masz odpowiednich uprawnień!'

    def get(self, request):
        form = StatisticsCreateForm()
        return render(request, "statistics_create.html", {'form': form})

    def post(self, request):
        form = StatisticsCreateForm(request.POST)
        if form.is_valid():
            user = request.user
            if user.has_perm('website_basketball.add_statistics'):
                Statistics.objects.create(team=form.cleaned_data['team'],
                                          matches_played=form.cleaned_data['matches_played'],
                                          total_points=form.cleaned_data['total_points'],
                                          total_wins=form.cleaned_data['total_wins'])
                return redirect('/statistics/')
            else:
                return render(request, "403.html")
        else:
            return render(request, "statistics_create.html", {'form': form, 'info': "Wypełnij poprawnie formularz!"})

    """ Aby móc wejść na tą podstronę trzeba mieć uprawnienie, po wejściu metodą GET wyświetla pusty formularz,
     a po wejściu metodą POST wysyła formularz gdy jest poprawny i zapisuje dane do bazy """


class StatisticsShowView(View):
    def get(self, request):
        statistics = Statistics.objects.all().order_by('team')
        return render(request, "statistics_show.html", {'statistics': statistics})

    """ Wyświetla Wszystkie zapisane statystyki ułożone po kolei nazwami drużyn """


class TeamShowView(View):
    def get(self, request):
        team = Team.objects.all().order_by('team_name')
        return render(request, "team_show.html", {'team': team})

    """ Wyświetla stworzone drużyny ułożone po kolei poprzez ich nazwy """


class TeamCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = TeamCreateForm()
        return render(request, "team_create.html", {'form': form})

    def post(self, request):
        form = TeamCreateForm(request.POST)
        if form.is_valid():
            team = Team.objects.create(team_name=form.cleaned_data['team_name'])
            players = form.cleaned_data['players']
            for p in players:
                p.team = team
                p.save()
            return redirect("/team/")
        else:
            return render(request, "team_create.html", {'form': form, 'info': "Wypełnij poprawnie formularz!"})
    """ Po wejściu metodą GET wyświetla pusty formularz dodania drużyny,
        a po wejściu metodą POST zapisuje drużynę i graczy do bazy danych """


class TeamPlayerDeleteView(LoginRequiredMixin, View):
    def get(self, request):
        form = TeamPlayerDeleteForm()
        return render(request, "team_player_delete.html", {'form': form})

    def post(self, request):
        form = TeamPlayerDeleteForm(request.POST)
        if form.is_valid():
            team = Team.objects.get(team_name=form.cleaned_data['team'])
            delete_player = form.cleaned_data['delete_player']
            for p in delete_player:
                p.team = None
                p.save()
            return redirect('/team/', {'info': 'Gracz pomyślnie usunięty!'})
        else:
            return render(request, "team_player_delete.html", {'form': form, 'info': 'Wypełnij poprawnie formularz!'})

    """ Po wejściu na stronę wyświetla formularz,
        a gdy wyślę się formularz zp oprawnymi danymi usuwa gracza z danej drużyny """


class TeamPlayerAddView(LoginRequiredMixin, View):
    def get(self, request):
        form = TeamPlayerAddForm()
        return render(request, "team_player_add.html", {'form': form})

    def post(self, request):
        form = TeamPlayerAddForm(request.POST)
        if form.is_valid():
            add_player = form.cleaned_data['add_player']
            team = Team.objects.get(team_name=form.cleaned_data['team'])
            for p in add_player:
                p.team = team
                p.save()
            return redirect('/team/', {'info': 'Gracz pomyślnie dodany!'})
        else:
            return render(request, "team_player_add.html", {'form': form, 'info': 'Wypełnij poprawnie formularz!'})

    """ Po wejściu metodą GET wyświetli formularz dodania gracza do drużyny,
        a po wejściu POST wyśle formularz i doda gracza do odpowiedniej drużyny"""


class PlayerEditView(LoginRequiredMixin, View):
    def get(self, request):
        form = UserEditForm()
        return render(request, "user_edit.html", {'form': form})

    def post(self, request):
        user = request.user
        form = UserEditForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            password = form.cleaned_data['password']
            player = Player.objects.get(id=user.id)
            player.first_name = first_name
            player.last_name = last_name
            player.set_password(password)
            player.save()
            return redirect("/login/")
        else:
            return render(request, "user_edit.html", {'form': form, 'info': "Wypełnij poprawnie formularz!"})

    """ Po wejściu na stronę metodą GET wyświetli formularz edycji profilu,
        a po wejściu POST wyśle formularz i zapisze dane do bazy o ile będą poprawne"""


class TournamentsListView(View):
    def get(self, request):
        tournament = Tournament.objects.all()
        team = Team.objects.all()
        return render(request, "tournament_list.html", {'tournament': tournament, 'team': team})

    """ Pokazuje listę Turniejów oraz drużyn biorących w nim udział"""


class TournamentCreateView(PermissionRequiredMixin, View):
    permission_required = 'website_basketball.add_tournament'

    def get(self, request):
        form = TournamentCreateForm()
        return render(request, "tournament_create.html", {'form': form})

    def post(self, request):
        form = TournamentCreateForm(request.POST)
        if form.is_valid():
            user = request.user
            if user.has_perm('website_basketball.add_tournament'):
                tournament = Tournament.objects.create(name=form.cleaned_data['name'])
                team = form.cleaned_data['team']
                for t in team:
                    t.tournament = tournament
                    t.save()
                return redirect('/tournament/')
            else:
                return render(request, "403.html")
        else:
            return render(request, "tournament_create.html", {'form': form, 'info': "Wypełnij poprawnie formularz!"})

    """ Aby wejść potrzebne jest uprawnienie, po wejściu GET Wyświetli pusty formularz,
        a po wejściu POST wyślę formularz doda turniej do bazy danych oraz drużyny przypisane do tego turnieju"""


class TournamentTableView(View):

website_basketball/templates/history_matches.html
{% extends "home_page.html" %}
{% block content %}
<ul>
    <li><a href="/stadium-match-create/">Zapisz rozgrywkę</a></li>
    <li><a href="/stadium-create/">Stwórz stadion</a></li>
</ul>
    <h2>Wyszukaj mecz w historii</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Znajdź">

    </form>
        <h1>{{ info }}</h1>
        <h2>{{ stadium.name }}</h2>

        <li>
            <b>Drużyna:</b> {{ team.team_name }}
        </li>
        <li>
            <b>Data rozegrania spotkania:</b>{{ stadium.date }}
        </li>

{% endblock %}

website_basketball/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logowanie</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css">
</head>
<body>
    <h1>Witaj {{ user.username }} na stronie logowania</h1>
    <h3> Zaloguj się by przejść dalej</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zaloguj">
        {{ info }}
    </form>
</body>
</html>

website_basketball/templates/match_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edycja drużyny</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css">
</head>
<body>
<button><a href="/stadium-history/">Powrót</a></button>
    <h2>Zapisz mecz</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zapisz">
        {{ info }}
    </form>
</body>
</html>

website_basketball/templates/stadium_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css">
</head>
<body>
<button><a href="/stadium-history/">Powrót</a></button>
    <h2>Stwórz stadion</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Stwórz stadion">
            {{ info }}
        </form>
</body>
</html>















{% extends "home_page.html" %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Stwórz stadion">
        {{ info }}
    </form>
{% endblock %}

website_basketball/templates/statistics_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edycja drużyny</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css">
</head>
<body>
<button><a href="/statistics/">Powrót</a></button>
    <h2>Dodaj statystykę</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Utwórz">
        {{ info }}
    </form>
</body>
</html>

website_basketball/templates/statistics_show.html
{% extends "home_page.html" %}
{% block content %}
    <body>
    <ul>
        <li><a href="/statistics-create/">Stwórz statystyki</a></li>
    </ul>

        <ul>
            {% for static in statistics %}
            <li>
                {{ static.team }}
                {{ static.matches_played }}
                {{ static.total_points }}
                {{ static.total_wins }}
                    {% for s in static.stadium_set.all %}
                        {{ s.statistics }}
                    {% endfor %}
            </li>
            {% endfor %}
            {{ info }}
        </ul>
    </body>
{% endblock %}

website_basketball/templates/table_new.html
<!DOCTYPE HTML>
<html lang="pl">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Koszykówka</title>
	<link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One|Open+Sans" rel="stylesheet">
	<link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
	<div class="tournament">
  <!-- tournament logo -->
  <div class="tournament__logo-container tournament__logo-container--right">
    <strong class="tournament__logo tournament__logo--gold"></strong>
  </div>
  <div class="tournament__grid">
    <!-- tournament__round 1/8 -->
    <div class="tournament__round tournament__round--first-round">
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
    </div>

    <div class="tournament__round tournament__round--first-round">
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
    </div>

    <!-- tournament__round 1/2 -->
    <div class="tournament__round">
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
    </div>

    <!-- tournament__round final -->
    <div class="tournament__round tournament__round--final">
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
    </div>

    <!-- tournament__round winner -->
    <div class="tournament__round tournament__round--winner">
      <div class="tournament__match">
        <a class="tournament__match__team" href="#">Lorem ipsum.</a>
      </div>
    </div>
  </div>

</div>
</body>
</html>

website_basketball/templates/team_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tworzenie drużyny</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css">
    <button><a href="/team/">Powrót</a></button>
</head>
<body>
    <h2>Stwórz drużynę</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Stwórz drużynę">
        {{ info }}
    </form>
</body>
</html>

website_basketball/templates/team_player_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edycja drużyny</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css">
</head>
<body>
<a href="/team/">Powrót</a>
    <h2>Dodaj członka do drużyny</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zapisz zmiany">
        {{ info }}
    </form>

</body>
</html>

website_basketball/templates/team_player_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edycja drużyny</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css">
</head>
<body>
<a href="/team/">Powrót</a>
    <h2>Usuń członka drużyny</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Usuń">
        {{ info }}
    </form>
</body>
</html>

website_basketball/templates/team_wins_add.html
{% extends "home_page.html" %}
{% block content %}
<h2>Dodaj zwycięstwo drużyny</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Dodaj wygraną" name="add_win">
        {{ info }}
    </form>
{% endblock %}

website_basketball/templates/tournament_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css">
</head>
<body>
<button><a href="/tournament/">Powrót</a></button>
    <h2>Stwórz turniej</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Stwórz turniej">
        {{ info }}
    </form>
</body>
</html>

website_basketball/templates/tournament_list.html
{% extends "home_page.html" %}
{% block content %}
    <body>
    <ul>
        <li>
            <a href="/tournament-create/">Stwórz turniej</a>
        </li>
    </ul>

        <ul>
            {% for t in tournament %}
            <li>
                {{ t.name }}
                    {% for team in t.team_set.all %}
                        <b>-</b> {{ team.team_name }}
                    {% endfor %}
            </li>
            {% endfor %}
            {{ info }}
        </ul>
    </body>
{% endblock %}

website_basketball/templates/tournament_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="table.css">
    <title>Tabela turnieju</title>
</head>
<body>

      <div class="tournament">
    <!-- tournament logo -->
    <div class="tournament__logo-container tournament__logo-container--right">
      <strong class="tournament__logo tournament__logo--gold"></strong>
    </div>
    <div class="tournament__grid">
      <!-- tournament__round 1/8 -->
      <div class="tournament__round tournament__round--first-round">
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
        </div>
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
        </div>
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
        </div>
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
        </div>
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
        </div>
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
        </div>
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
        </div>
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
          <a class="tournament__match__team" href="#">{{ team.name }}</a>
        </div>
      </div>
      <!-- tournament__round 1/4 -->
      <div class="tournament__round tournament__round--first-round">
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team_stage_2.name }}</a>
          <a class="tournament__match__team" href="#">{{ team_stage_2.name }}</a>
        </div>
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team_stage_2.name }}</a>
          <a class="tournament__match__team" href="#">{{ team_stage_2.name }}</a>
        </div>
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team_stage_2.name }}</a>
          <a class="tournament__match__team" href="#">{{ team_stage_2.name }}</a>
        </div>
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team_stage_2.name }}</a>
          <a class="tournament__match__team" href="#">{{ team_stage_2.name }}</a>
        </div>
      </div>

      <!-- tournament__round 1/2 -->
      <div class="tournament__round">
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team_stage_3.name }}</a>
          <a class="tournament__match__team" href="#">{{ team_stage_3.name }}</a>
        </div>
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team_stage_3.name }}</a>
          <a class="tournament__match__team" href="#">{{ team_stage_3.name }}</a>
        </div>
      </div>

      <!-- tournament__round final -->
      <div class="tournament__round tournament__round--final">
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team_final.name }}</a>
          <a class="tournament__match__team" href="#">{{ team_final.name }}</a>
        </div>
      </div>

      <!-- tournament__round winner -->
      <div class="tournament__round tournament__round--winner">
        <div class="tournament__match">
          <a class="tournament__match__team" href="#">{{ team_win.name }}</a>
        </div>
      </div>
    </div>
  </div>
</body>

</body>
</html>